In [1]:
import numpy as np
import pandas as pd
import time

from scipy.sparse import coo_matrix, tril, triu, eye, diags, csc_matrix
from scipy.sparse.linalg import spsolve_triangular, inv

In [2]:
df = pd.read_table("Dataset/stanweb.dat", header=None)

In [3]:
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

In [4]:
P

<281903x281903 sparse matrix of type '<class 'numpy.float64'>'
	with 2382912 stored elements in COOrdinate format>

# Power Method a = 0.85

In [6]:
a = 0.85

In [7]:
stime=time.time()
x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
print("Power method with a=0.85 took: ",time.time()-stime,"seconds to converge")

Power method with a=0.85 took:  1.0920600891113281 seconds to converge


In [8]:
top=np.arange(x.shape[1])
(top[np.argsort(-x)]+1).flatten()[:50]

array([ 89073, 226411, 241454, 262860, 134832, 234704, 136821,  68889,
       105607,  69358,  67756, 225872, 186750,  95163, 251796, 272442,
       119479, 231363,  55788, 167295, 179645,  38342, 117152, 198090,
        60210, 235496, 132695, 181701, 247241, 259455,  62478, 120708,
       161890,  77999,  17781, 176790, 137632, 221087, 183004,  96745,
       112742, 145892, 151428,  81435,  60440, 208542,     91, 214128,
       258348, 222873])

# Power method a=0.99

In [5]:
a = 0.99;

In [6]:
stime=time.time()
x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
print("Power method with a=0.85 took: ",time.time()-stime,"seconds to converge")

Power method with a=0.85 took:  18.383810997009277 seconds to converge


In [7]:
top=np.arange(x.shape[1])
(top[np.argsort(-x)]+1).flatten()[:50]

array([ 89073, 281772, 174665, 226411, 179645, 271409, 262860, 136821,
        68889,  77988, 116530,  95163, 272442, 251796,  65580, 119479,
       241454, 245765,  58048,  14785,  77084, 117152, 152337, 181701,
       235496, 259455, 247241,  62478, 120708,  77999, 221087, 183004,
       176790, 137632,  17781,  96745, 119822,  27904, 272762,  96196,
       229580,  95366, 169234, 234962, 236644, 275885,  85040,  58612,
       264187,  49047])

# Gauss Seidel

In [5]:
a = 0.85

In [6]:
P_dense=P.tocsc()[P.tocsc().getnnz(0)>0][:,P.getnnz(0)>0]

In [7]:
dim=P_dense.shape[0]

In [8]:
b=np.ones((dim,1))/dim
y=(1-a)*np.ones((dim,1))/dim

In [9]:
L=tril(P_dense,-1)+eye(dim)
U=triu(P_dense).tocsr()
D=diags(U.diagonal())

In [10]:
x=spsolve_triangular(L,(-U@y+b))

In [11]:
stime=time.time()
i=0
while(np.linalg.norm(x-y)>10e-8 and i != 10):
    y = x                            
    x=spsolve_triangular(L,(-U@y+b))
    i+=1
print("Power method with a=0.85 took: ",time.time()-stime,"seconds to converge")

Power method with a=0.85 took:  21.85254955291748 seconds to converge


In [12]:
x=x.T
top=np.arange(x.shape[1])
(top[np.argsort(-x)]+1).flatten()[:50]

array([ 18398, 112399, 140596, 112473, 140544,  42787,  68900, 192517,
       225228, 247005, 192861, 248431, 113220, 113277,    261, 113346,
       166729, 168300, 175255,  23467,  58740, 247000, 113815, 112206,
       163442,  95156, 252104, 174837, 252078, 159893, 141009, 110370,
        11688,  23194,  93693,  15165, 203824, 111172,  94031, 224772,
        59700, 111671,  42834, 193269, 111930, 111083, 191879, 113890,
       218911, 116339])

## Creating a new page X

In [5]:
df=df.append(pd.DataFrame([[int(np.max(df)[0]+1),int(np.max(df)[0]+1),0]],index=[len(df)]))

In [6]:
a=0.85
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
    
top=np.arange(x.shape[1])
np.where(top[np.argsort(-x)]+1==281904)
# top[np.argsort(-x)]=top
# np.where((top+1)==281904)

(array([0], dtype=int64), array([281903], dtype=int64))

## Creating page Y

In [7]:
df=df.append(pd.DataFrame([[int(np.max(df)[0]+1),int(np.max(df)[0]),1]],index=[len(df)]))

In [8]:
a=0.85
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
    
top=np.arange(x.shape[1])
np.where(top[np.argsort(-x)]+1==281904)
# top[np.argsort(-x)]=top
# np.where((top+1)==281904)

(array([0], dtype=int64), array([149077], dtype=int64))

## Creating page Z

In [9]:
df=df.append(pd.DataFrame([[int(np.max(df)[0]+1),int(np.max(df)[0]-1),1]],index=[len(df)]))

In [10]:
a=0.85
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
    
top=np.arange(x.shape[1])
np.where(top[np.argsort(-x)]+1==281904)
# top[np.argsort(-x)]=top
# np.where((top)==281904)

(array([0], dtype=int64), array([109086], dtype=int64))

## Create Links to popular pages

In [11]:
popular= [106732,    707,  98460,  38495, 172045,  29717,  30694,  62248,
        26196,   2749, 103169,  75873,  50827,  13493,  86973,  77721,
       128811,  45237, 227753,  47047,   3959,  79632,   3137,  23829,
        85494,  90808,  38392, 201481,  38611,  23437,  15019, 105729,
        60750,  43030,  33014,  73472, 151232,  26432, 108737, 124378,
        27341,  86210,   8080,  23115, 135364,  45181,   9062,  49391,
        20217,  10691]

## Make references to them from X

In [12]:
for page in popular:
    df=df.append(pd.DataFrame([[int(np.max(df)[0]-2),page,0.05]],index=[len(df)]))

In [13]:
a=0.85
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
    
top=np.arange(x.shape[1])
np.where(top[np.argsort(-x)]+1==281904)
# top[np.argsort(-x)]=top
# np.where((top)==281904)

(array([0], dtype=int64), array([109089], dtype=int64))

## Make references to them from Z and Y

In [14]:
for page in popular:
    df=df.append(pd.DataFrame([[int(np.max(df)[0]-1),page,0.05]],index=[len(df)]))
    df=df.append(pd.DataFrame([[int(np.max(df)[0]),page,0.05]],index=[len(df)]))

In [15]:
a=0.85
dim=np.max(df[0])
P=coo_matrix((df[2], (df[0]-1, df[1]-1)), shape=(dim, dim))
b=np.ones((dim,1))/dim
y=np.ones((dim,1))/dim
filt=P.getnnz(1)>0
tol = 10^-8;

x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
while(np.linalg.norm(x-y.T)>10e-8):
    y = x.T                             
    x = a*y.T*P + (a*y.T*filt+(1-a))*b.T
    
top=np.arange(x.shape[1])
np.where(top[np.argsort(-x)]+1==281904)
# top[np.argsort(-x)]=top
# np.where((top)==281904)

(array([0], dtype=int64), array([109091], dtype=int64))

In [34]:
df

0       1         2
0             1    6548  0.500000
1             1   15409  0.500000
2             2  252915  0.032258
3             2  246897  0.032258
4             2  251658  0.032258
5             2  280935  0.032258
6             2  213966  0.032258
7             2  243294  0.032258
8             2  225119  0.032258
9             2  241596  0.032258
10            2  178642  0.032258
11            2  210870  0.032258
12            2  204189  0.032258
13            2  190453  0.032258
14            2  204604  0.032258
15            2  181714  0.032258
16            2  164599  0.032258
17            2  175799  0.032258
18            2  163550  0.032258
19            2  140864  0.032258
20            2  115926  0.032258
21            2   73764  0.032258
22            2  105730  0.032258
23            2   98628  0.032258
24            2   84477  0.032258
25            2  105318  0.032258
26            2  100193  0.032258
27            2  102355  0.032258
28            2   64930  0.032258
29            2   54582  0.032258
...         ...     ...       ...
2383034  281904   73472  0.050000
2383035  281905   73472  0.050000
2383036  281904  151232  0.050000
2383037  281905  151232  0.050000
2383038  281904   26432  0.050000
2383039  281905   26432  0.050000
2383040  281904  108737  0.050000
2383041  281905  108737  0.050000
2383042  281904  124378  0.050000
2383043  281905  124378  0.050000
2383044  281904   27341  0.050000
2383045  281905   27341  0.050000
2383046  281904   86210  0.050000
2383047  281905   86210  0.050000
2383048  281904    8080  0.050000
2383049  281905    8080  0.050000
2383050  281904   23115  0.050000
2383051  281905   23115  0.050000
2383052  281904  135364  0.050000
2383053  281905  135364  0.050000
2383054  281904   45181  0.050000
2383055  281905   45181  0.050000
2383056  281904    9062  0.050000
2383057  281905    9062  0.050000
2383058  281904   49391  0.050000
2383059  281905   49391  0.050000
2383060  281904   20217  0.050000
2383061  281905   20217  0.050000
2383062  281904   10691  0.050000
2383063  281905   10691  0.050000

[2383064 rows x 3 columns]